name: Deploy Production

on:
  push:
    branches:
      - prod

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      NX_BASE_HREF: ${{ secrets.NX_BASE_HREF }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Docker Image with BuildKit Cache
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/maishaweb:latest
          cache-from: type=gha
          cache-to: type=gha
          build-args: |
            NX_BASE_HREF=${{ secrets.NX_BASE_HREF }}
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker pull ghcr.io/${{ github.repository_owner }}/maishaweb:latest
            docker stop maishaweb || true
            docker rm maishaweb || true
            docker run -d --name maishaweb \
            -l "traefik.http.routers.maishaweb.rule=Host(\`healthymaisha.com\`) && PathPrefix(\`/web\`)" \
            -l "traefik.http.routers.maishaweb.middlewares=maishawebpathstrip@docker" \
            -l "traefik.http.middlewares.maishawebpathstrip.stripprefix.prefixes=/web" \
            -l "traefik.http.middlewares.maishaweb.stripprefix.prefixes=/web" \
            -l "traefik.http.routers.maishaweb.service=maishaweb"  \
            -l "traefik.http.services.maishaweb.loadbalancer.server.port=80"  \
            -l "traefik.http.routers.maishaweb.tls=true"  \
            -l "traefik.http.routers.maishaweb.tls.certresolver=certresolverAlt"  \
            -l "traefik.http.routers.maishaweb.tls.domains[0].main=healthymaisha.com"  \
            -l "traefik.http.routers.maishaweb.tls.domains[0].sans=*.healthymaisha.com" \
            -l "traefik.http.routers.maishaweb.entrypoints=websecure" \
            -e NX_ENVIRONMENT=${{ env.NX_ENVIRONMENT }} \
            -e NX_BASE_HREF=${{ env.NX_BASE_HREF }} \
            -p 4201:80 \
            ghcr.io/${{ github.repository_owner }}/maishaweb:latest
