name: Deploy Production

on:
  push:
    branches:
      - prod

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      NX_BASE_HREF: ${{ secrets.NX_BASE_HREF }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Docker Image with BuildKit Cache
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/maishaweb:latest
          cache-from: type=gha
          cache-to: type=gha
          build-args: |
            NX_BASE_HREF=${{ secrets.NX_BASE_HREF }}

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CONTABO_IP }}
          username: ${{ secrets.CONTABO_USERNAME }}
          key: ${{ secrets.CONTABO_SSH_KEY }}
          script: |
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker pull ghcr.io/${{ github.repository_owner }}/maishaweb:latest
            docker stop maishaweb || true
            docker rm maishaweb || true
            docker run -d --name maishaweb \
            -p 8001:80 \
            -p 8443:443 \
            -e NX_ENVIRONMENT=${{ env.NX_ENVIRONMENT }} \
            -e NX_BASE_HREF=${{ env.NX_BASE_HREF }} \
            ghcr.io/${{ github.repository_owner }}/maishaweb:latest
            systemctl restart caddy
